Fix dw_uart build
The dw_uart build broke with:
  Commit 357d7fcc6
  In <stdio.h> provide only necessary types

The above commit exposed a latent missing-header bug:
-------------------------->8---------------------
In file included from ../../../../../../libgloss/arc/dw_uart/common/console_io.c:40:
../../../../../../libgloss/arc/dw_uart/device/device_hal/inc/dev_uart.h:81:2: error: unknown type name 'uint32_t'
   81 |  uint32_t len; /*!< buffer length in bytes */
      |  ^~~~~~~~
-------------------------->8---------------------

Fix by including <stdint.h>.

Inspired by 90a4ab5eb "Fix nano-malloc build".

Signed-off-by: Alexey Brodkin <abrodkin@synopsys.com>